import Foundation

public struct HTMLExporter: Sendable {

    public init() {}

    public func export(_ result: ScanResult) -> String {
        let criticalItems = result.items.filter { $0.riskLevel == .critical }
        let highItems = result.items.filter { $0.riskLevel == .high }
        let mediumItems = result.items.filter { $0.riskLevel == .medium }
        let lowItems = result.items.filter { $0.riskLevel == .low }
        let infoItems = result.items.filter { $0.riskLevel == .informational }

        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>LaunchAudit Report — \(result.hostname)</title>
            <style>
                * { box-sizing: border-box; margin: 0; padding: 0; }
                body { font-family: -apple-system, BlinkMacSystemFont, 'SF Pro', system-ui, sans-serif;
                       line-height: 1.5; color: #1d1d1f; background: #f5f5f7; padding: 24px; }
                .container { max-width: 1200px; margin: 0 auto; }
                h1 { font-size: 28px; margin-bottom: 4px; }
                h2 { font-size: 20px; margin: 24px 0 12px; border-bottom: 1px solid #d2d2d7; padding-bottom: 4px; }
                .meta { color: #86868b; font-size: 14px; margin-bottom: 24px; }
                .summary { display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin-bottom: 24px; }
                .card { background: white; border-radius: 12px; padding: 16px; text-align: center;
                        box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
                .card .num { font-size: 32px; font-weight: 700; }
                .card .label { font-size: 12px; color: #86868b; text-transform: uppercase; }
                .critical .num { color: #ff3b30; }
                .high .num { color: #ff9500; }
                .medium .num { color: #ffcc00; }
                .low .num { color: #34c759; }
                table { width: 100%; border-collapse: collapse; background: white;
                        border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08);
                        margin-bottom: 24px; }
                th { background: #f5f5f7; text-align: left; padding: 8px 12px; font-size: 12px;
                     text-transform: uppercase; color: #86868b; }
                td { padding: 8px 12px; border-top: 1px solid #f0f0f0; font-size: 13px; }
                tr:hover td { background: #fafafa; }
                .badge { display: inline-block; padding: 2px 8px; border-radius: 10px;
                         font-size: 11px; font-weight: 600; color: white; }
                .badge-critical { background: #ff3b30; }
                .badge-high { background: #ff9500; }
                .badge-medium { background: #ffcc00; color: #1d1d1f; }
                .badge-low { background: #34c759; }
                .badge-informational { background: #86868b; }
                .mono { font-family: 'SF Mono', Menlo, monospace; font-size: 12px; }
                .section { margin-bottom: 32px; }
                details { background: white; border-radius: 12px; padding: 12px 16px;
                          box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 8px; }
                summary { cursor: pointer; font-weight: 600; }
                footer { text-align: center; color: #86868b; font-size: 12px; margin-top: 48px; }
            </style>
        </head>
        <body>
        <div class="container">
            <h1>LaunchAudit Report</h1>
            <p class="meta">
                \(result.hostname) &middot;
                \(result.osVersion) &middot;
                Scanned \(result.scanDate.formatted()) &middot;
                \(result.items.count) items in \(String(format: "%.1f", result.scanDuration))s
            </p>

            <div class="summary">
                <div class="card"><div class="num">\(result.items.count)</div><div class="label">Total Items</div></div>
                <div class="card critical"><div class="num">\(criticalItems.count)</div><div class="label">Critical</div></div>
                <div class="card high"><div class="num">\(highItems.count)</div><div class="label">High</div></div>
                <div class="card medium"><div class="num">\(mediumItems.count)</div><div class="label">Medium</div></div>
                <div class="card low"><div class="num">\(lowItems.count + infoItems.count)</div><div class="label">Low / Info</div></div>
            </div>

        \(attentionSection(critical: criticalItems, high: highItems))

        \(categoryTables(result))

            <footer>
                Generated by LaunchAudit &middot; \(result.scanDate.formatted())
            </footer>
        </div>
        </body>
        </html>
        """
    }

    private func attentionSection(critical: [PersistenceItem], high: [PersistenceItem]) -> String {
        let items = critical + high
        guard !items.isEmpty else { return "" }

        var html = "<h2>Attention Required</h2>\n<table>\n"
        html += "<tr><th>Risk</th><th>Name</th><th>Category</th><th>Reason</th></tr>\n"
        for item in items {
            let badgeClass = "badge-\(item.riskLevel.rawValue)"
            let reason = item.riskReasons.first ?? ""
            html += """
            <tr>
                <td><span class="badge \(badgeClass)">\(item.riskLevel.displayName)</span></td>
                <td>\(escapeHTML(item.name))</td>
                <td>\(item.category.displayName)</td>
                <td>\(escapeHTML(reason))</td>
            </tr>

            """
        }
        html += "</table>\n"
        return html
    }

    private func categoryTables(_ result: ScanResult) -> String {
        var html = "<h2>All Items by Category</h2>\n"
        let grouped = Dictionary(grouping: result.items, by: \.category)

        for category in PersistenceCategory.allCases {
            guard let items = grouped[category], !items.isEmpty else { continue }

            html += """
            <details>
                <summary>\(category.displayName) (\(items.count))</summary>
                <table>
                <tr><th>Risk</th><th>Name</th><th>Status</th><th>Signed</th><th>Path</th></tr>

            """
            for item in items.sorted(by: { $0.riskLevel > $1.riskLevel }) {
                let badgeClass = "badge-\(item.riskLevel.rawValue)"
                let signed = item.signingInfo?.isSigned == true ? "Yes" : (item.signingInfo != nil ? "No" : "--")
                let path = item.configPath ?? item.executablePath ?? ""
                html += """
                <tr>
                    <td><span class="badge \(badgeClass)">\(item.riskLevel.displayName)</span></td>
                    <td>\(escapeHTML(item.name))</td>
                    <td>\(item.isEnabled ? "Enabled" : "Disabled")</td>
                    <td>\(signed)</td>
                    <td class="mono">\(escapeHTML(path))</td>
                </tr>

                """
            }
            html += "</table>\n</details>\n"
        }

        return html
    }

    private func escapeHTML(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }
}
